
CREATE SEQUENCE seq_data START WITH 1;
CREATE SEQUENCE seq_experiments START WITH 1;
CREATE SEQUENCE seq_treatments START WITH 1;
CREATE SEQUENCE seq_users START WITH 1;
CREATE SEQUENCE seq_variables START WITH 1;
CREATE SEQUENCE seq_version_change_log START WITH 1;